version: '3'
services:
  mysql:
    container_name: flask_mysql
    # let's grab from mysql 5.7 image
    image: mysql:5.7
    volumes:
        # pass volume named mysql-data to mysql container
      - mysql-data:/var/lib/mysql
    restart: unless-stopped
    labels:
      project: "flask"
    ports:
      - "3306:3306"
    environment:
      # credentials
      MYSQL_ROOT_PASSWORD: mypassword24#
      MYSQL_DATABASE: flask
      MYSQL_USER: flask
      MYSQL_PASSWORD: mypassword24#

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin:latest
    container_name: flask_phpmyadmin
    restart: unless-stopped
    labels:
      project: "flask"
    ports:
      - "5010:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: flask
      PMA_PASSWORD: mypassword24#
      MYSQL_ROOT_PASSWORD: mypassword24#

# volumes definition here
volumes:
  # just a persistance data
  mysql-data:
    driver: local